on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Before uses'
        run: ls

      - uses: actions/checkout@v3

      - name: 'After uses'
        run: ls


